[General]
network = edgetrustsim.EdgeTrustNetwork
sim-time-limit = 100s
repeat = 1

# TraCI (SUMO) integration
**.scenarioFile = "../../../simulator/sumo/edgetrust_scenario/scenario.sumocfg"
**.traci.host = "localhost"
**.traci.port = 9999
**.traci.autoShutdown = true

# Let OMNeT++ know we are using the Veins mobility models
*.vehicle[*].mobility.typename = "veins::TraCIMobility"
