//
// Generated file, do not edit! Created by opp_msgtool 6.4 from veins/modules/application/edgetrust/EdgeTrustSafetyMessage.msg.
//

#ifndef __VEINS_EDGETRUSTSAFETYMESSAGE_M_H
#define __VEINS_EDGETRUSTSAFETYMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0604
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class EdgeTrustSafetyMessage;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/DemoSafetyMessage_m.h" // import veins.modules.messages.DemoSafetyMessage


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/edgetrust/EdgeTrustSafetyMessage.msg:8</tt> by opp_msgtool.
 * <pre>
 * packet EdgeTrustSafetyMessage extends DemoSafetyMessage
 * {
 *     int senderId = 0;
 *     double heading = 0.0;
 *     double acceleration = 0.0;
 *     int sequenceNumber = 0;
 *     int retransmissionCount = 0;
 *     bool isMalicious = false;
 *     int attackType = 0; // 0=None, 1=FDI, 2=Blackhole, 3=Sybil, 4=DoS
 * }
 * </pre>
 */
class VEINS_API EdgeTrustSafetyMessage : public ::veins::DemoSafetyMessage
{
  protected:
    int senderId = 0;
    double heading = 0.0;
    double acceleration = 0.0;
    int sequenceNumber = 0;
    int retransmissionCount = 0;
    bool isMalicious_ = false;
    int attackType = 0;

  private:
    void copy(const EdgeTrustSafetyMessage& other);

  protected:
    bool operator==(const EdgeTrustSafetyMessage&) = delete;

  public:
    EdgeTrustSafetyMessage(const char *name=nullptr, short kind=0);
    EdgeTrustSafetyMessage(const EdgeTrustSafetyMessage& other);
    virtual ~EdgeTrustSafetyMessage();
    EdgeTrustSafetyMessage& operator=(const EdgeTrustSafetyMessage& other);
    virtual EdgeTrustSafetyMessage *dup() const override {return new EdgeTrustSafetyMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual double getHeading() const;
    virtual void setHeading(double heading);

    virtual double getAcceleration() const;
    virtual void setAcceleration(double acceleration);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual int getRetransmissionCount() const;
    virtual void setRetransmissionCount(int retransmissionCount);

    virtual bool isMalicious() const;
    virtual void setIsMalicious(bool isMalicious);

    virtual int getAttackType() const;
    virtual void setAttackType(int attackType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const EdgeTrustSafetyMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, EdgeTrustSafetyMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::EdgeTrustSafetyMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::EdgeTrustSafetyMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_EDGETRUSTSAFETYMESSAGE_M_H

